### ISSUE TITLE
UI.toast throws a TypeError exception

### ISSUE THREAD

**Issue by jjjdddrrr** [shajul/termux-api#3]
I have the following issue using termux.UI on an ASUS ZenFone3 with Android 8.0...
>>> from termux.UI import toast
>>> toast('hello')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/termux/UI.py", line 169, in toast
    return execute(f'termux-toast {options} "{text}"')['output']
TypeError: tuple indices must be integers or slices, not str
>>>
The toast appears as expected.
Currently, the toast call must be put in a try block to catch the exception, or else replaced entirely by...
os.system('termux-toast hello').
Otherwise, a great package. Hope this helps.

**Comment by shajul** [comment]
Thanks for reporting.. fixed in new version
