### ISSUE TITLE
termux.android.execute('termux-dialog confirm -t 'Hello world!') results in error + unexpected behavior

### ISSUE THREAD

**Issue by MartyX98** [shajul/termux-api#4]
Hello!

Calling

![Screenshot_20211123_161741.jpg](https://user-images.githubusercontent.com/93448002/143052165-bff594fe-3ff5-45fe-9886-a8a0767a917d.jpg)

results in

![Screenshot_20211123_161801.jpg](https://user-images.githubusercontent.com/93448002/143052246-42be6123-a053-41ed-9308-f4ad9c8127e0.jpg)

The execute() function cannot handle strings with spaces as arguments (such as "Hello world!"). This does not happen when there are no spaces in the string.

What I would expect is the same as when calling the API outside of python:

![Screenshot_20211123_161833.jpg](https://user-images.githubusercontent.com/93448002/143052743-1baac892-3820-4be4-89ee-b80590989b6d.jpg)

results in: 

![Screenshot_20211123_161858.jpg](https://user-images.githubusercontent.com/93448002/143052810-237277c0-6d7b-4aa0-8721-172d437cfc36.jpg)

One unexpected behavior I have noticed is that any string argument that gets passed through the execute() function (such as title, hint and maybe more, i haven't tried all) will be quoted when displayed:

![Screenshot_20211123_162934_com.termux.api.jpg](https://user-images.githubusercontent.com/93448002/143053904-43ed7ca0-a559-47d0-a4b8-423e3e25e930.jpg)

Expected behavior would be:

![Screenshot_20211123_163030_com.termux.api.jpg](https://user-images.githubusercontent.com/93448002/143053970-faef4131-2d09-460a-b4fb-a0e89ccb083a.jpg)

**Comment by MartyX98** [comment]
I think this is due to the the "fSplit = func.split()" in android.py on line 24. May I suggest using built-in shlex.split() instead of string.split() ? shlex.split() can preserve quoted substring. Looking at the code, that might solve the unexpected behavior with the quotes as well i think.

**Comment by shajul** [comment]
Thanks.. will fix
