### ISSUE TITLE
Cannot set clipboard with a str that contains line break

### ISSUE THREAD

**Issue by Young-Lord** [shajul/termux-api#6]
For example:
```python
In [8]: termux.Clipboard.setclipboard("aaa\r\nbbb\rccc\nddd")
Out[8]: (0, '', '')

In [9]: termux.Clipboard.getclipboard()
Out[9]: (0, 'aaa bbb ccc ddd', '')
```

the `\r` and `\n` are changed into ` `(space)

**Comment by Young-Lord** [comment]
I use this as a solution:
```python
subprocess.Popen("termux-clipboard-set", shell=True, stdin=subprocess.PIPE, stdout=subprocess.PIPE).communicate(st.encode("utf-8"))
```

**Comment by shajul** [comment]
the input is split before it is sent to subprocess so that arbitrary code cannot be executed as a security measure, hence the problem. solution is easy, but maybe not good for production environment

**Comment by Young-Lord** [comment]
> the input is split before it is sent to subprocess so that arbitrary code cannot be executed as a security measure, hence the problem. solution is easy, but maybe not good for production environment

I know that, but `termux-clipboard-set` can pass content by stdin, does that still has a secutiry issue?

**Comment by shajul** [comment]
Please send me a pull request.. I'll merge it
